### PR TITLE
enable user_visible_url for command/shell jobs

### PR DESCRIPTION
**Pull request by kongomongo**
hi there. would really love to be able to do this for command/shell jobs. 

I have lots of jobs that are cumbersome to get via default url job because of special cookie setup or websocket connections etc. , so I put them in .sh scripts and run them as command jobs. However I cant make clickable url in my HtmlReporter.

The only thing I'm a bit puzzled about is `LOCATION_IS_URL` which should really be a function ?

### CODE REVIEW

**Comment by kongomongo** [comment]
hrm why is this failing

**Comment by kongomongo** [comment]
alright, back on topic ;-)

**Comment by Sveder** [comment]
This is a great idea - 👍

**Review by thp — CHANGES_REQUESTED** [review]
Should this be part of `JobBase` instead, so that it can also be used for overriding the URL/location of any kind of job (and in this sense, rename it `user_visible_location`, since not all jobs have a URL as such).

**Comment by kongomongo** [comment]
> Should this be part of `JobBase` instead, so that it can also be used for overriding the URL/location of any kind of job (and in this sense, rename it `user_visible_location`, since not all jobs have a URL as such).

I agree. Still, what do you suggest for the LOCATION_IS_URL variable? Should this be a function that just does a regex match if location is a URI?

**Comment by thp** [comment]
> > Should this be part of `JobBase` instead, so that it can also be used for overriding the URL/location of any kind of job (and in this sense, rename it `user_visible_location`, since not all jobs have a URL as such).
> 
> I agree. Still, what do you suggest for the LOCATION_IS_URL variable? Should this be a function that just does a regex match if location is a URI?

Yeah, a regex match would most likely do the trick.

**Comment by kongomongo** [comment]
@thp Can you have a look? I added a very simple regex.

Disclaimer: I have NOT tested the code at runtime.

**Review by thp — CHANGES_REQUESTED** [review]
Whoops, I just realized now that `user_visible_url` as key was already released in version 2.22, so (even though I requested this earlier) we shouldn't rename the key (as to not break existing user's configurations). The rest of the code seems fine, and moving from url job to job base is also fine (also moving in the documentation is fine).

It's just so that existing 2.22 configurations with `user_visible_url` set should still work when upgrading to a newer release.

The rest is fine, and `location_is_url()` also looks sane from here..

**Comment by kongomongo** [comment]
OK I changed it back. So now the only "breaking" change could be that if someone had user_visible_url set to "www.mystuff.com" then it is now not set as a location anymore now due to the regex only picking up true URI (http:// ftp://, etc). But I guess even in that case a HTML displaying device will make that a link anyways?

**Comment by kongomongo** [comment]
just for reference... https://github.com/thp/urlwatch/issues/608

**Review by thp — APPROVED** [review]

**Comment by thp** [comment]
Thanks!

**Pull request merged**
