### PR TITLE
New option: ignore_incomplete_reads

### PR DESCRIPTION
**Pull request by wfrisch**
Fixes https://github.com/thp/urlwatch/issues/725

### CODE REVIEW

**Review by thp — CHANGES_REQUESTED** [review]
No need to update manpages (will be done on release), but please add an entry to `CHANGELOG.md` describing the changes.

**Comment by wfrisch** [comment]
> No need to update manpages (will be done on release), but please add an entry to `CHANGELOG.md` describing the changes.

Thanks for the review. It should be OK now.

**Comment by wfrisch** [comment]
For completeness' sake, here's a deliberately broken web server that emulates this error class:
https://gist.github.com/wfrisch/63d1163645fa01e3ab1296e752769359

**Review by thp — APPROVED** [review]
Thanks!

**Pull request merged**
