### PR TITLE
shrink container image from 1g to 150m

### PR DESCRIPTION
**Pull request by sedlund**
The original container build weighed in at 1.03g.  I switched it to the latest stable python 3.11.0 image based on Alpine Linux and this brings it down to 151m.  I tested with the latest stable with their Debian bullseye slim image and it comes to 228m.

I also converted the container to run as a user instead of root and use pip to install from local.

Let me know what you think.

### CODE REVIEW

**Comment by sedlund** [comment]
Wanted to tag @chenrui333 and @agix for comments

**Review by agix — APPROVED** [review]
Sounds good to me

**Comment by sedlund** [comment]
Hi @thp, I think I completed the needful, if not let me know.  Thanks.

**Comment by thp** [comment]
Merged, thanks!

**Pull request merged**
