### PR TITLE
Cumulative changes: 'pdf2text' filter, fix 'format-json' to handle utf-8, add viewport to HTML

### PR DESCRIPTION
**Pull request by mborsetti**
A few fixes and the introduction of a filter to transform PDF files to text (see https://github.com/thp/urlwatch/issues/68 and https://github.com/thp/urlwatch/issues/183).  Fixed an issue with 'format-json' to handle utf-8 and added viewport to HTML

### CODE REVIEW

**Comment by cfbao** [comment]
* I believe it's best practice to limit a PR to a single issue rather than a cumulative update.

* We should probably design a more general mechanism to handle `str` or `bytes` output/input. Deciding by finding one particular filter in the filter list is rather ad hoc. Other filters (e.g. `sha1sum`, `hexdump` and potential custom filters in `hooks.py`) may also use a binary input, and new job types (including custom ones) shouldn't need to worry about every filter's expectation.

* `format-json` already handles Unicode characters correctly. It's simply that it escapes them rather than keeping them as is. It's probably best to leave `ensure_ascii` as a user adjustable option and default to old behaviour to ensure backwards compatibility.

**Comment by thp** [comment]
(btw, those are all great changes that I would like to see in urlwatch, so if you don't want to split them up into separate PRs, let me know, I can also cherry-pick changes manually for you)

**Comment by mborsetti** [comment]
> (btw, those are all great changes that I would like to see in urlwatch, so if you don't want to split them up into separate PRs, let me know, I can also cherry-pick changes manually for you)

**@thp**,

Thanks.  I am new to git/github and this is a nights & weekends project -- you've motivated me to work on learning more about using git/github and resubmit. Most likely not before the weekend (US time).

**Comment by thp** [comment]
They way I'd do it is probably:

For each "group" of changes, `git checkout master`, then `git checkout -b name-of-feature` then `git cherry-pick COMMIT1 COMMIT2 ...` (where `COMMIT1` and `COMMIT2`, ... are the commit IDs of the commits you want to put into that branch) and then push + make a PR.

**Comment by mborsetti** [comment]
I finally had enough free time to learn enough git to be dangerous! :)

Separate pull requests have been placed.

**THANKS** so much for the tips; I would have never found `git cherry-pick` without your hint, and I am so glad I did.

**Pull request closed without merging**
