### PR TITLE
fixing github example

### PR DESCRIPTION
**Pull request by oxivanisher**

### CODE REVIEW

**Comment by oxivanisher** [comment]
This will fix the Github example in the documentation.

**Comment by oxivanisher** [comment]
My changes are so simple, there must be another reason why the travis pipeline failes.

**Comment by kongomongo** [comment]
Seems like the travis tests use the repo instead of this PR's changes?

https://travis-ci.org/github/thp/urlwatch/jobs/753906480

___________ test_url[https://github.com/thp/urlwatch/releases-job20] ___________
url = 'https://github.com/thp/urlwatch/releases'
job = {'filter': [{'xpath': '(//div[contains(@class,"release-header")]//a)[1]'}, {'html2text': 're'}, 'strip'], 'url': 

<snip>

        output_data = d['output']
>       assert input_data == output_data
E       AssertionError: assert '' == '2.18'
E         - 2.18

**Review by thp — CHANGES_REQUESTED** [review]
This fails, because the filter examples are tested using static test data in `lib/urlwatch/tests/data/filter_documentation_testdata.yaml`. You need to update the data there and then the build will go through. Currently it has this in there:
```
https://github.com/thp/urlwatch/releases:
  input: |-
    <div class="release-timeline-tags release-entry">
      <h4 class="flex-auto min-width-0 pr-2 pb-1 commit-title">
        <a href="/thp/urlwatch/releases/tag/2.18">
          2.18
        </a>
      </h4>
    </div>
  output: |-
    2.18
```

**Comment by thp** [comment]
By the way, the current filter example still works fine for me?

**Pull request closed without merging**
