### PR TITLE
Add missing requests import for mailgun

### PR DESCRIPTION
**Pull request by ad-m**
See #113

### CODE REVIEW

**Comment by sbraz** [comment]
@ad-m Why would you not display an error if requests is not found? urlwatch requires it anyway.

**Comment by ad-m** [comment]
@sbraz , I proportioned to the style of old code (see https://github.com/ad-m/urlwatch/blob/dee9868055a17cf4c1ca104d30fce2ebd89d7ffa/lib/urlwatch/reporters.py#L49 ).

**Comment by sbraz** [comment]
Well pushbullet is optional, requests isn't. Anyway, no big deal :)

**Comment by ad-m** [comment]
requests is required only by ``MailGunReporter``. pushbullet is required only by ``PushbulletReport``. I don't see any differences. Using both of reporters are not required.

**Comment by sbraz** [comment]
Requests is _not_ optional. urlwatch depends on it: https://github.com/thp/urlwatch/blob/master/setup.py#L16

**Comment by ad-m** [comment]
@sbraz , you are right.

**Pull request merged**
