### PR TITLE
Use base64 module for Py3k compatibility

### LINKED ISSUE #26: username:password@url domains do not work after Python3k conversion.
With the py3k conversion ( ` ./convert-to-python3.sh` ) for urlwatch URLs with the pattern `http://username:password@localhost/` do not work. 

urlwatch crashes with:
```
File "/nix/store/sv62w8czrr5pziwwkgi67xw2vbc3swrs-python3.4-urlwatch-1.18/bin/.urlwatch-wrapped", line 307, in <module>
raise exception
File "/nix/store/4z7g0rlc27nwyq1mfn57kiijnnqn2swk-python3-3.4.3/lib/python3.4/concurrent/futures/thread.py", line 54, in run
result = self.fn(*self.args, **self.kwargs)
File "/nix/store/sv62w8czrr5pziwwkgi67xw2vbc3swrs-python3.4-urlwatch-1.18/bin/.urlwatch-wrapped", line 288, in process_job
data = job.retrieve(timestamp, filter_func, headers, log)
File "/nix/store/sv62w8czrr5pziwwkgi67xw2vbc3swrs-python3.4-urlwatch-1.18/lib/python3.4/site-packages/urlwatch/handler.py", line 142, in retrieve
parts.password)).encode('base64').strip())
LookupError: 'base64' is not a text encoding; use codecs.encode() to handle arbitrary codecs
```

This issue does not occur when using python2 instead.

Initially i opened a ticket at https://github.com/NixOS/nixpkgs/issues/12021

### PR DESCRIPTION
**Pull request by thp**
Fixes #26

### CODE REVIEW

**Comment by thp** [comment]
@makefu Can you check if this fixes your issue with the Py3k conversion?

**Comment by makefu** [comment]
Hi, with this revision (e788b6e) i get the following error for the url `http://guest:@cvs2svn.tigris.org/svn/cvs2svn/trunk` :
```
Traceback (most recent call last):
  File "/nix/store/c25iks221pfzq18j9q9lf5w1cy0kkz27-python3.4-urlwatch-1.18/bin/.urlwatch-wrapped", line 307, in <module>
    raise exception
  File "/nix/store/lwz7kmb4jzgh3da04p1pa723i6084xk0-python3-3.4.3/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/nix/store/c25iks221pfzq18j9q9lf5w1cy0kkz27-python3.4-urlwatch-1.18/bin/.urlwatch-wrapped", line 288, in process_job
    data = job.retrieve(timestamp, filter_func, headers, log)
  File "/nix/store/c25iks221pfzq18j9q9lf5w1cy0kkz27-python3.4-urlwatch-1.18/lib/python3.4/site-packages/urlwatch/handler.py", line 143, in retrieve
    headers['Authorization'] = 'Basic %s' % (base64.b64encode(auth_token).strip())
  File "/nix/store/lwz7kmb4jzgh3da04p1pa723i6084xk0-python3-3.4.3/lib/python3.4/base64.py", line 62, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
TypeError: 'str' does not support the buffer interface
```

**Comment by makefu** [comment]
@thp can you revise/reopen the issue as the problem persists ... Thanks :D

**Comment by thp** [comment]
Reopened #26

**Pull request merged**
