### PR TITLE
Basic colorization for wdiff-style differences in HtmlReporter (previ…

### PR DESCRIPTION
**Pull request by kongomongo**
…ously only in StdoutReporter)

Hi there. Small pull request to get the wdiff style colorization in HtmlReporter (Emails) in addition to the terminal colorized output.

### CODE REVIEW

**Comment by mborsetti** [comment]
You should check out the _webchanges_ fork at https://pypi.org/project/webchanges/, optimized for HTML.  It contains all the PRs that improved HTML reporting that were not accepted by this project, including:
* Markdown, e.g. the output from ``html2text`` filter (f.k.a. ``pyhtml2text``), is reconstructed into HTML: formatting such as bolding, italics, underlining list bullets, etc. as well as, most importantly, clickable links, is preserved
* **uses color and strikethrough to mark added and deleted lines**
* long lines wrap around and other legibility improvements
* rendered correctly by email clients who override stylesheets (e.g. Gmail)

It also has a new [additions_only](https://webchanges.readthedocs.io/en/latest/diff_filters.html#additions-only) filter that makes it easier to track content that was added without the distractions of the content that was deleted.

Example

Try it out, and if you like it please contribute!

**Comment by kongomongo** [comment]
hi mborsetti,

thanks for your suggestion. Before I dive in: this is specifically adding html diff highlighting to wdiff style output. Can webchanges handle that?

Many thanks

**Comment by mborsetti** [comment]
>  Before I dive in: this is specifically adding html diff highlighting to wdiff style output. Can webchanges handle that?

Good question: I initially missed the '**w**' in 'wdiff'! 

The unreleased version should do the html colorization you're looking for:

image

Install it using `pip install git+https://github.com/mborsetti/webchanges.git@unreleased` (git needs to be [installed](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git))

**Review by thp — APPROVED** [review]
Cool, thanks!

**Review by thp — CHANGES_REQUESTED** [review]
@kongomongo Can you still fix the whitespace issues that CI is complaining about?

```
/home/travis/build/thp/urlwatch/lib/urlwatch/reporters.py:208:82: E226 missing whitespace around arithmetic operator
/home/travis/build/thp/urlwatch/lib/urlwatch/reporters.py:208:93: E226 missing whitespace around arithmetic operator
/home/travis/build/thp/urlwatch/lib/urlwatch/reporters.py:209:84: E226 missing whitespace around arithmetic operator
/home/travis/build/thp/urlwatch/lib/urlwatch/reporters.py:209:95: E226 missing whitespace around arithmetic operator
```

**Comment by kongomongo** [comment]
that should do the trick

**Review by thp — APPROVED** [review]
Yup, thanks :)

**Pull request merged**
